travis:
  secure:
    BINSTAR_TOKEN: hn28e3SROp43cZEwbo/kpUVvbuXj2WWnHicixh1Jn5YaRMqhbziCN40C5Kx6mKQVyxgKd3DbG4LS4RMmKSsShZK0YHf4zoO/KzPheg0cOMXiTOn+Yf3GjcHKYp0UkxOhGEq/icqM9Cj0R7fsAdTK9AQGZ2zvuLVSPdO1YXPHzpm59KqvrOH84Rb2Szh23vEG+e4A3urqgOtbdhz+7b8NEg1fk3ZzDRk/dJ+3fOOSOuJcyvbd3pVL+ZE7sNHKhQ1Ylb9jB3b4xAhXrt6NKtrambQPlSOB35pkx2TGF8EjfnBB24jO2YK0XzSfYV/sDHE+g7zw6Q6BBsY4j77/BUvd359KbgTddMW4v6F0ubZfaGuADN8soVLI8rjwfaNxa/+HdUn6L7t6icn4+Slz7kR26QLG4qnr7mm0R7Ce2KoU8ME6OyTaoLd9S6t2/nWP36OU3jKm+rJoWLZNK9+1gxVF0RpFgvESs5odjvazGjOqCvbEIuTycGkVPq6sCXtKetI4YdLjBB3ImX3Vq55wZSGIYo448uNCZ/qkH9LNiqU+T0v8SBSx9LR9ntlnFaOSFo1be1Ej4/TYeAtl0NU7iAfQIl2v7AVzDAMLVw2gMKJZntyl0Qcg3W5fV23nDtPhHdmqbWk00dUWDeIhHnydbPjMcw1jq2d6HMlWrNJerTpqJYI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
