travis:
  secure:
    BINSTAR_TOKEN: uNKNxu4B4pMKALCJrd/OkO7hND7wz2YloNAs6SW7q1hspJ8lqkE78OwwsgEGZj4qxPmsKu1UF3+BvUNOKsEe9gb0BGourGe9lTWqmBfedRL/8l21JVV5kzgnY2lgsUbz7FjZ4ReiMUzamfmC4NMIDW9UK5xDQbYfdhL9epvVIISYo53lkdG5xqt86tFiN/4ZXCMFxVxghF9+APlXSLxqzJBQolTiGGEeneVZMr9UG+H7mX1fteoAO0nFAhe6S6ebl8If40kYIWd8qupHdZHVh2h+cfJS7NPwLt/zyJtczMe4E7Wk2x+g5gYRDPd9N2KCcch2wypsKrcINJUwWhIticpvErMe/2fndamsuCe6Qdqvtxej5FBH5s1VlWSNe8A7/VgiIx+hFXJWzNe9rLQHLhos/gPzgK/B0M1U8vqYYoZuyVDw5I26c9TQr/AZhwKp7V4RU9JZsl3HsTgk3ZIUaOPtVEdx9gH1wEQXewjYYYsYpyUeQbzjgfqmFqMJSVygJpm2hG7jaJJCa3vibeCI/BiUExoYZ6kFHMLcz7p54FC8aCdMLd9GYg/tfhecYtIPnUiToRpNWCpxij2b0LgVy5IL/QZxTsAOCKbkstwfwq8mbUkCzgvuJxmIeJcmSxGrcepyq4qwRtAoFZGJulhSbQ1Zi7zHTBSZbL0lZ08AUvg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
